apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet
  template:
    metadata:
      labels:
        app: pet

    spec:
      containers:
        - name: pet
          image: jp.icr.io/ns-v1/pet
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
